#!/bin/bash
#SBATCH -J ctxgraph-long12h
#SBATCH -o ctxgraph-long12h.%j.out
#SBATCH -e ctxgraph-long12h.%j.err
#SBATCH -p gh
#SBATCH -N 8
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=72
#SBATCH -t 12:00:00
#SBATCH -A AST24021

set -euo pipefail

if [ -n "${SLURM_SUBMIT_DIR:-}" ] && [ -f "${SLURM_SUBMIT_DIR}/scripts/run_alfworld_ctxgraph_30b_ghdev_8n_memory_polish.sh" ]; then
  SCRIPT_DIR="${SLURM_SUBMIT_DIR}/scripts"
else
  SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
fi
RUN_STAMP=${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}

export SRUN_PARTITION=${SRUN_PARTITION:-gh}
export SRUN_TIME=${SRUN_TIME:-12:00:00}

# The 2h probe averaged roughly 18 minutes per PPO step with rollout.n=4.
# rollout.n=8 roughly doubles trajectories per PPO step, so use fewer steps
# and keep checkpoint cadence near 20% of the run.
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-16}
export SAVE_FREQ=${SAVE_FREQ:-3}
export TEST_FREQ=${TEST_FREQ:--1}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-ctxgraph_alfworld_30b_8n_promptfix_p16384_r16384_12h_${RUN_STAMP}}
export DATA_N_TRAIN=${DATA_N_TRAIN:-128}
export DATA_N_VAL=${DATA_N_VAL:-16}
export CHECKPOINT_BASE=${CHECKPOINT_BASE:-/scratch/07144/yw23374/vista/checkpoints/context-graph}
export MAX_ACTOR_CKPT_TO_KEEP=${MAX_ACTOR_CKPT_TO_KEEP:-2}
export MAX_CRITIC_CKPT_TO_KEEP=${MAX_CRITIC_CKPT_TO_KEEP:-2}
export HF_SYNC_CHECKPOINTS=${HF_SYNC_CHECKPOINTS:-1}
export HF_SYNC_REQUIRED=${HF_SYNC_REQUIRED:-1}

export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.35}
export ROLLOUT_ENFORCE_EAGER=${ROLLOUT_ENFORCE_EAGER:-True}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-8192}
export ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS:-64}
export ROLLOUT_PROMPT_LENGTH=${ROLLOUT_PROMPT_LENGTH:-16384}
export ROLLOUT_RESPONSE_LENGTH=${ROLLOUT_RESPONSE_LENGTH:-16384}
export ROLLOUT_LOG_PROB_MAX_LEN=${ROLLOUT_LOG_PROB_MAX_LEN:-32768}
export ROLLOUT_N=${ROLLOUT_N:-8}

export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-16}
export DATA_MAX_PROMPT_LENGTH=${DATA_MAX_PROMPT_LENGTH:-16384}
export DATA_MAX_RESPONSE_LENGTH=${DATA_MAX_RESPONSE_LENGTH:-16384}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-8}
export ACTOR_PPO_MAX_TOKEN_LEN=${ACTOR_PPO_MAX_TOKEN_LEN:-32768}
export ACTOR_PPO_INFER_MAX_TOKEN_LEN=${ACTOR_PPO_INFER_MAX_TOKEN_LEN:-32768}
export ACTOR_PARAM_OFFLOAD=${ACTOR_PARAM_OFFLOAD:-True}
export ACTOR_OPTIMIZER_OFFLOAD=${ACTOR_OPTIMIZER_OFFLOAD:-True}

export PLUGIN_MAX_TURN=${PLUGIN_MAX_TURN:-20}
export PLUGIN_TURN_MAX_NEW_TOKENS=${PLUGIN_TURN_MAX_NEW_TOKENS:-512}
export PLUGIN_MAX_SESSION=${PLUGIN_MAX_SESSION:-4}
export PLUGIN_VAL_MAX_SESSION=${PLUGIN_VAL_MAX_SESSION:-4}
export PLUGIN_BRANCH_LEN=${PLUGIN_BRANCH_LEN:-8192}
export PLUGIN_MAX_TRAJ=${PLUGIN_MAX_TRAJ:-6}
export PLUGIN_VAL_MAX_TURN=${PLUGIN_VAL_MAX_TURN:-20}
export PLUGIN_VAL_RESPONSE_LENGTH=${PLUGIN_VAL_RESPONSE_LENGTH:-16384}

exec bash "${SCRIPT_DIR}/run_alfworld_ctxgraph_30b_ghdev_8n_memory_polish.sh"
