#!/usr/bin/env python3
"""Scan ScienceAgentBench gold programs for imports missing from the env.

Because the sandbox now HARD-BLOCKS pip/conda (envs/scienceagent_sandbox.py),
every package a task needs must be pre-installed in the `cxtgraph` conda env.
This script finds the gap: it walks all gold programs, collects their
top-level imports, and reports which ones are NOT importable in the current
interpreter — i.e. the set you must `pip install` so those tasks become
solvable instead of dying on an ImportError.

Run on Vista (inside the cxtgraph env, so find_spec reflects what's installed):

    conda activate cxtgraph
    python scripts/scan_sab_missing_imports.py \
        --gold-dir data/sab_benchmark/gold_programs \
        --out requirements_sab_missing.txt

Then review the file (verify the PyPI names — import name != PyPI name for a
few), install, and re-run the smoke:

    pip install -r requirements_sab_missing.txt
"""

from __future__ import annotations

import argparse
import ast
import glob
import importlib.util
import os
import sys


# Import name -> PyPI distribution name, for the common cases where they differ.
# Anything not in here is emitted as-is with a "# verify" marker.
_IMPORT_TO_PYPI = {
    "cv2": "opencv-python",
    "sklearn": "scikit-learn",
    "skimage": "scikit-image",
    "PIL": "Pillow",
    "yaml": "PyYAML",
    "bs4": "beautifulsoup4",
    "Bio": "biopython",
    "osgeo": "GDAL",
    "torch_geometric": "torch-geometric",
    "torch_scatter": "torch-scatter",
    "torch_sparse": "torch-sparse",
    "OpenSSL": "pyOpenSSL",
    "dateutil": "python-dateutil",
    "DeepPurpose": "DeepPurpose",
}

# Top-level names that are stdlib or otherwise never pip-installed — ignore.
_IGNORE = {
    "os", "sys", "re", "json", "math", "random", "time", "datetime", "typing",
    "collections", "itertools", "functools", "pathlib", "argparse", "io",
    "warnings", "logging", "subprocess", "shutil", "glob", "copy", "pickle",
    "csv", "tempfile", "abc", "enum", "dataclasses", "string", "operator",
    "__future__", "ast", "importlib", "inspect", "hashlib", "gzip", "zipfile",
    "traceback", "threading", "multiprocessing", "contextlib", "uuid",
}


def _top_level_imports(path: str) -> set[str]:
    try:
        src = open(path, encoding="utf-8", errors="ignore").read()
        tree = ast.parse(src)
    except (SyntaxError, OSError):
        return set()
    mods: set[str] = set()
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            mods |= {a.name.split(".")[0] for a in n.names}
        elif isinstance(n, ast.ImportFrom) and n.level == 0 and n.module:
            mods.add(n.module.split(".")[0])
    return mods


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gold-dir", default="data/sab_benchmark/gold_programs",
                    help="Directory tree containing the 102 gold *.py programs")
    ap.add_argument("--out", default=None,
                    help="Write a requirements file here (else print to stdout)")
    args = ap.parse_args()

    if not os.path.isdir(args.gold_dir):
        print(f"ERROR: gold dir not found: {args.gold_dir}", file=sys.stderr)
        print("       (unpack the benchmark zip first; see the eval sbatch header)",
              file=sys.stderr)
        return 1

    gold = glob.glob(os.path.join(args.gold_dir, "**", "*.py"), recursive=True)
    if not gold:
        print(f"ERROR: no .py files under {args.gold_dir}", file=sys.stderr)
        return 1

    all_mods: set[str] = set()
    for p in gold:
        all_mods |= _top_level_imports(p)
    all_mods -= _IGNORE

    missing = sorted(m for m in all_mods
                     if importlib.util.find_spec(m) is None)

    print(f"[scan] {len(gold)} gold programs, {len(all_mods)} distinct "
          f"third-party imports, {len(missing)} MISSING", file=sys.stderr)

    lines = [
        "# Auto-generated by scripts/scan_sab_missing_imports.py — packages",
        "# imported by gold programs but NOT importable in the current env.",
        "# VERIFY each PyPI name before installing (import name != PyPI name",
        "# for some; unknown ones are marked).",
        "",
    ]
    for m in missing:
        if m in _IMPORT_TO_PYPI:
            lines.append(_IMPORT_TO_PYPI[m])
        else:
            lines.append(f"{m}  # verify PyPI name (import name = {m})")

    text = "\n".join(lines) + "\n"
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"[scan] wrote {len(missing)} entries -> {args.out}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
