#!/bin/bash
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/work/09281/chc_1996/vista/context-graph}
cd "$PROJECT_ROOT"

SAB_REAL_EVAL=${SAB_REAL_EVAL:-1}
SAB_VAL_MAX_SAMPLES=${SAB_VAL_MAX_SAMPLES:-4}
SAB_TRAIN_MAX_SAMPLES=${SAB_TRAIN_MAX_SAMPLES:-8}
SAB_RESPONSE_LENGTH=${SAB_RESPONSE_LENGTH:-4096}
SAB_VAL_MAX_TURN=${SAB_VAL_MAX_TURN:-8}
SAB_TURN_MAX_NEW_TOKENS=${SAB_TURN_MAX_NEW_TOKENS:-512}

echo "Submitting 30B Instruct SAB smoke:"
echo "  SAB_REAL_EVAL=$SAB_REAL_EVAL"
echo "  SAB_VAL_MAX_SAMPLES=$SAB_VAL_MAX_SAMPLES"
echo "  SAB_TRAIN_MAX_SAMPLES=$SAB_TRAIN_MAX_SAMPLES"
echo "  SAB_RESPONSE_LENGTH=$SAB_RESPONSE_LENGTH"
echo "  SAB_VAL_MAX_TURN=$SAB_VAL_MAX_TURN"
echo "  SAB_TURN_MAX_NEW_TOKENS=$SAB_TURN_MAX_NEW_TOKENS"

sbatch \
  --export=ALL,SAB_REAL_EVAL="$SAB_REAL_EVAL",SAB_VAL_MAX_SAMPLES="$SAB_VAL_MAX_SAMPLES",SAB_TRAIN_MAX_SAMPLES="$SAB_TRAIN_MAX_SAMPLES",SAB_RESPONSE_LENGTH="$SAB_RESPONSE_LENGTH",SAB_VAL_MAX_TURN="$SAB_VAL_MAX_TURN",SAB_TURN_MAX_NEW_TOKENS="$SAB_TURN_MAX_NEW_TOKENS" \
  scripts/eval_sab_react_30b_instruct_8node_smoke.sh
